[net]
git-fetch-with-cli = true

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clinker-features=-lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clinker-features=-lld"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"

[target.aarch64-pc-windows-msvc]
linker = "lld-link"