[net]
git-fetch-with-cli = true

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clinker-features=-lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clinker-features=-lld"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "target-feature=+crt-static"]

[build]
incremental=true
rustflags=["-C", "codegen-units=16"]
rustc-wrapper="sccache"

